### ISSUE TITLE
Suddenly stopped clock synchorization

### ISSUE THREAD

**Issue by larruda** [larruda/ciandt_tt#8]
Since last Sunday (25th January) the app stopped to sync with the server's clock through a public web-service. No app updates have been sent at all, nothing's changed. Probably some was made on TT's endpoint. 

Need to investigate further.

**Comment by jpjcjbr** [comment]
I tryed to find an explanation for this problem and I figured out that it can be something related to CORS(http://en.wikipedia.org/wiki/Cross-origin_resource_sharing), is there any special handling for this?

We could ask tt admins if they could add the following header in the requests/responses "Access-Control-Allow-Origin: *"

I was debugging and I received this error message "XMLHttpRequest cannot load https://tt.ciandt.com/.net/index.ashx/GetClockDeviceInfo?deviceID=2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access", it seems to be something related to CORS.

**Comment by jpjcjbr** [comment]
@larruda I create an API, using apiary.io, with CORS enabled and I set the return to have the same content of TT's request and the time was loaded correctly.

If we can't change TT server to accept CORS requests we could create a Heroku application with CORS enabled to act as a proxy for us.

**Comment by larruda** [comment]
@jpjcjbr thanks a lot for the hard work on this, dude!
Just tell me something: did you get this CORS error message by debugging on your browser or by running it on an Android device and checking adb's log output?

**Comment by jpjcjbr** [comment]
@larruda I've just tested on my browser, I don't know if this is valid test, but when I changed the url it started working

I'll work on a proxy server for TT's API and try to debug it on a real device after that I'll let you know

**Comment by larruda** [comment]
Hey, our IT staff discovered that the real issue is due to an invalid certificate error on TT's endpoint, just as I thought. They fixed the certificate and the app started working properly again. I'm closing this them, alright?  Thanks!

**Comment by larruda** [comment]
Sorry @jpjcjbr I forgot to explain to you why I asked that above.

It happens that all regular browsers cannot do a cross-domain request by default because this represents a very critical security breach for potential attackers to explore on websites. This is called "Same origin policy". As you stated, the browser blocks the request and error out if no CORS headers are present on the HTTP response message.

Although, you can turn-off this security measure on some browsers. See how it's done on Chrome: http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome
By doing that you can debug cross-domain requests with no problem at all.

That's why I asked if you were using your browser or not. Android's Webview do not implement this policy thus we can bypass the issue. 

If you have any further questions please let me know.
Thanks again for all the help!

**Comment by jpjcjbr** [comment]
Ahhh ok, thanks for the explanation @larruda
